name: Say Hello

on:
  merge_request:
    branches:
      - main

jobs:
  increase-version:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo "Hello, world!"