name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: 
    - main

jobs:
  Testing-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: |
          echo "Jean Ruiz is testing out GitHub Actions 🚀"